joypads:
  - type:   keyboard
    player: 1
    # arrows-[up/down/left/right] and keypad-[1..9] also usable
    mapping:
      dpad-up:    w
      dpad-down:  s
      dpad-left:  a
      dpad-right: d
      select:     j
      start:      k
      a:          n
      b:          m
  - type:             controller
    player:           2
    controller_index: 1

#resolution:
#  width: 768
#  height: 720

display-fps: false

show_menu: true

#new_controller_replaces_player_one: true

speed: 100 #%