joypads:
  - type:             controller
    controller_index: 1
  - type: keyboard
    mapping:
      dpad-up:    w
      dpad-down:  s
      dpad-left:  a
      dpad-right: d
      select:     j
      start:      k
      a:          n
      b:          m