resolution:
  width: 768
  height: 720

display-fps: true

joypads:
  - type: keyboard
    mapping:
      dpad-up:    w
      dpad-down:  s
      dpad-left:  a
      dpad-right: d
      select:     j
      start:      k
      a:          n
      b:          m
  - type:             controller
    controller_index: 1
#  - type: keyboard
#    mapping:
#      dpad-up:    arrows-up
#      dpad-down:  arrows-down
#      dpad-left:  arrows-left
#      dpad-right: arrows-right
#      select:     keypad-5
#      start:      keypad-6
#      a:          keypad-2
#      b:          keypad-3