joypads:
  - type:   keyboard
    player: 1
    # arrows-[up/down/left/right] and keypad-[1..9] also usable
    mapping:
      dpad-up:    w
      dpad-down:  s
      dpad-left:  a
      dpad-right: d
      select:     j
      start:      k
      a:          n
      b:          m
  - type:             keyboard
    player:           2
    mapping:
      dpad-up:    arrows-up
      dpad-down:  arrows-down
      dpad-left:  arrows-left
      dpad-right: arrows-right
      select:     keypad-4
      start:      keypad-5
      a:          keypad-1
      b:          keypad-2

#rom: smb.nes

#resolution:
#  width: 768
#  height: 720

#display_fps: false

#show_menu: true

#new_controller_replaces_player_one: true

#speed: 100 #%

#vsync: false